import type { Metadata } from "next";
import "@/styles/globals.css";
import { GameProvider } from "@/context/GameContext";
import { Sour_Gummy } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SourGummy = Sour_Gummy({
  weight: ["600", "700", "800", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={SourGummy.className}>
        <GameProvider>{children}</GameProvider>
      </body>
    </html>
  );
}
